- id: shfmt
  name: shfmt
  description: Shell source code formatter (native install)
  language: golang
  # Note: keep Go version in `go.mod` in sync with shfmt's required Go version
  additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.7.0]
  entry: shfmt
  args: [-w, -s]
  types: [shell]
  exclude_types: [csh, tcsh, zsh]
  stages: [commit, merge-commit, push, manual]

- id: shfmt-docker
  name: shfmt
  description: Shell source code formatter (Docker image)
  language: docker_image
  # Note: use the top level multiplatform image digest here
  entry: --net none mvdan/shfmt:v3.7.0@sha256:c029770b8d8091b482cd1b30bd190d1d422bb5787e6ddc7894ef7d9784578690
  args: [-w, -s]
  types: [shell]
  exclude_types: [csh, tcsh, zsh]
  stages: [commit, merge-commit, push, manual]
