- id: shfmt
  name: shfmt
  description: Shell source code formatter (native install)
  language: golang
  # Note: keep Go version in `go.mod` in sync with shfmt's required Go version
  additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.6.0]
  entry: shfmt
  args: [-w, -s]
  types: [shell]
  stages: [commit, merge-commit, push, manual]

- id: shfmt-docker
  name: shfmt
  description: Shell source code formatter (Docker image)
  language: docker_image
  # Note: use the top level multiplatform image digest here
  entry: --net none mvdan/shfmt:v3.6.0@sha256:b68b0e33bf799f393aec27f72da64ec1d84476c8cfa9a2a7bfd0cbbdbfc8d534
  args: [-w, -s]
  types: [shell]
  stages: [commit, merge-commit, push, manual]
