name: Main push and PR checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # No caching as we're expected to run rarely
      - name: Install dependencies and run checks
        run: |
          set -euxo pipefail
          python3 -m pip install pre-commit
          export PRE_COMMIT_COLOR=always
          pre-commit try-repo . --files .github/workflows/test-good.sh
          for hook in shfmt shfmt-docker; do
            ! pre-commit try-repo . $hook --files .github/workflows/test-bad.sh
            ! git diff --exit-code .github/workflows/test-bad.sh
            git restore .github/workflows/test-bad.sh
          done
